rating:
    css: '#productTitle'
    xpath: '//div[contains(concat(" ",normalize-space(@class)," ")," centerColAlign ")]//a[contains(concat(" ",normalize-space(@class)," ")," a-popover-trigger ")]'
    type: Text
title:
    css: '#productTitle'
    xpath: null
    type: Text
priceWhole:
    css: 'div.centerColAlign span.a-price-whole'
    xpath: null
    type: Text
priceFraction:
    css: 'div.centerColAlign span.a-price-fraction'
    xpath: null
    type: Text
about:
    css: 'div.centerColAlign div.a-section.a-spacing-medium'
    xpath: null
    type: Text
seller:
    css: null
    xpath: '//div[contains(concat(" ",normalize-space(@class)," ")," centerColAlign ")]//div[contains(concat(" ",normalize-space(@class)," ")," a-section ")][contains(concat(" ",normalize-space(@class)," ")," a-spacing-none ")]//a[contains(concat(" ",normalize-space(@class)," ")," a-link-normal ")]'
    type: Text
description:
    css: 'p span'
    xpath: null
    type: Text
salesRank:
    css: 'td > span span:nth-of-type(1)'
    xpath: null
    type: Text
firstAvailable:
    css: 'div.a-section div.a-section tr:nth-of-type(4) td.a-size-base'
    xpath: null
    type: Text
images:
    css: '.imgTagWrapper img'
    xpath: null
    type: Attribute
    attribute: data-a-dynamic-image
technical:
    css: 'div.a-expander-content div.a-expander-content'
    xpath: null
    type: Text
categoryTree:
    css: 'div.a-subheader ul.a-unordered-list'
    xpath: null
    type: Text
